### ISSUE TITLE
Bug: markdown that has code comments with a tree file isn't rendering well

### ISSUE THREAD

**Issue by lirantal** [estruyf/screendown#3]
I think it just might be missing the new line (\r\n) sorta thing to render it well:

![image](https://user-images.githubusercontent.com/316371/220627419-2a0037b4-2e02-4c9f-80ed-9c9736fdc3ce.png)

**Comment by lirantal** [comment]
Per @estruyf's suggestion I added the `bash` code style and now it renders well:
![image](https://user-images.githubusercontent.com/316371/220627773-67d5f7f3-c614-4987-aa58-ca89c007a635.png)

I think we can probably close unless anyone has a good idea how to handle differently :)

**Comment by estruyf** [comment]
There is already a fix on its way for this 😄 - if you don't define the code type, it will use the default code element without syntax highlighting.

**Comment by estruyf** [comment]
Should be fixed in the `0.0.11` version, which is currently building/publishing.

**Comment by lirantal** [comment]
Nice, thank you!
