### ISSUE TITLE
[Suggestion] Trim description so you can tell what this does in VSCode

### ISSUE THREAD

**Issue by HebaruSan** [estruyf/screendown#7]
I can guess from the name that this extension probably has something to do with screenshots and markdown, but the description should make guessing unnecessary. It doesn't need to repeat the name, since it's already there in the listing, and claiming that it's "easy-to-use" just takes up space that could be spent on saying what it actually does:

![image](https://github.com/estruyf/screendown/assets/1559108/89083a79-9e06-42cc-aaee-e4560364f487)

**Comment by estruyf** [comment]
Thanks for the suggestion. I've updated it.
