### ISSUE TITLE
No math support?

### ISSUE THREAD

**Issue by dzx-dzx** [estruyf/screendown#8]
Looks like the inline `$$` isn't rendered. Will it be supported in the future?

**Comment by estruyf** [comment]
Math support is added in version `0.0.22`.

<img width="1404" alt="image" src="https://github.com/estruyf/screendown/assets/2900833/a954be35-0af8-406d-9b54-be5cc6966bbc">

Let me know if anything needs improvement, as I haven't used math in Markdown files.

**Comment by dzx-dzx** [comment]
In your own image there...seems to be a piece of "raw" equation (L = 21pv2SCL) following the rendered one? And I can observe it in my own environment.

**Comment by estruyf** [comment]
I took an online sample and looked similar, but it might be better that you test it and let me know if there are things to be improved or not.

**Comment by dzx-dzx** [comment]
<img width="1404" alt="294880608-a954be35-0af8-406d-9b54-be5cc6966bbc" src="https://github.com/estruyf/screendown/assets/31068367/f14ff14e-de41-4665-ba10-10691f648f5e">
I mean, the underscored part doesn't look like they should exist.

**Comment by estruyf** [comment]
It seems the Katex extension creates a math and HTML block. In version 0.0.23, the HTML block is hidden.

**Comment by dzx-dzx** [comment]
Perfect, thanks!
