### ISSUE TITLE
Support for other languages, why not?

### ISSUE THREAD

**Issue by talison-cardoso** [estruyf/screendown#9]
Looking for an extension to capture code snippets, I found _screendown_ and found all the flexibility offered to be sensational.
I understand that the purpose is to work with Markdown, but why wouldn't it be better to do this beautiful work with code snippets too? The extension can display the selected section, but it also has the 'selection' in the image. See below.

![image](https://github.com/estruyf/screendown/assets/132726516/1703ffd9-4dc8-4a63-be81-33e3fcf8dbf6)

I believe that this improvement would bring more people to keep the extension installed, because instead of having _screendown_ and another like _codespan_, it would be better to just have _screendown_.

**Note:** The purpose of this approach is to bring a suggestion for improvement, if it is not well seen and does not make sense with the essence of it, I apologize for the suggestion.
..
P.S. But that's my wish for the extension. I appreciate your understanding.

**Comment by estruyf** [comment]
Thanks @talison-cardoso, Screendown was already able to do this, but it seems that there are VSCode styles applied. A fix will be provided.

**Comment by estruyf** [comment]
It should have been fixed with release `0.0.21`.
